services:
  postgres:
    image: postgres:latest
    container_name: go_books_db
    environment:
      POSTGRES_USER: nuublx
      POSTGRES_PASSWORD: psgrPass
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: